[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "recipes2"
version = "0.1.0"
description = "A reusable Django recipes app"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["Django>=4.2"]

[tool.setuptools.packages.find]
where = ["."]
