# Generated by Django 5.2.3 on 2025-06-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='desc',
            field=models.CharField(default='description', max_length=400),
        ),
    ]
