# Generated by Django 5.2.3 on 2025-06-25 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_recipe_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='desc',
        ),
    ]
