# Generated by Django 5.2.3 on 2025-07-04 07:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0004_category_cuisine_ingredient_ingredientsource_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["position"]},
        ),
        migrations.AlterField(
            model_name="item",
            name="position",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="date_updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="step",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manager.stepgroup",
            ),
        ),
    ]
