# Generated by Django 5.2.3 on 2025-07-07 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0006_alter_item_group_conversion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversion",
            name="ingredient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manager.ingredient",
            ),
        ),
    ]
