# Generated by Django 5.2.3 on 2025-07-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0009_alter_conversion_factor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientprice",
            name="quantity",
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
