# Generated by Django 5.2.3 on 2025-07-12 06:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0011_alter_timer_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="date_created",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="date_updated",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
