# Generated by Django 5.2.3 on 2025-07-20 07:19

import recipes2.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0015_alter_recipe_cuisine"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="alt_text",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="show_in_gallery",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to=recipes2.models.image_upload_to),
        ),
    ]
