# Generated by Django 5.2.3 on 2025-07-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0018_itemcost_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("full_success", models.BooleanField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
