# Generated by Django 5.2.3 on 2025-07-22 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0021_rename_amount_recipecost_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipecost",
            name="amount_per_unit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="recipecost",
            name="yield_unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manager.yieldunit",
            ),
        ),
    ]
