# Generated by Django 5.2.5 on 2025-08-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0027_alter_diary_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tested',
            field=models.BooleanField(default=True),
        ),
    ]
