# Generated by Django 5.2.5 on 2025-08-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0028_alter_recipe_tested"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="show_in_gallery",
            field=models.BooleanField(default=True),
        ),
    ]
