# Generated by Django 5.2.5 on 2025-08-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0029_alter_image_show_in_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
