# Generated by Django 5.2.5 on 2025-08-11 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0030_alter_step_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['position']},
        ),
    ]
