# Generated by Django 5.2.5 on 2025-08-13 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0031_alter_step_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"ordering": ["position"]},
        ),
    ]
