# Generated by Django 5.2.5 on 2025-08-14 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0032_alter_image_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timer",
            options={"ordering": ["position"]},
        ),
    ]
