# Generated by Django 5.2.5 on 2025-08-15 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0033_alter_timer_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="unit",
            options={"ordering": ["singular"]},
        ),
        migrations.RenameField(
            model_name="unit",
            old_name="name",
            new_name="singular",
        ),
    ]
