# Generated by Django 5.2.5 on 2025-08-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0034_alter_unit_options_rename_name_unit_singular"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="plural",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
