# Generated by Django 5.2.5 on 2025-08-15 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0035_unit_plural"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="yieldunit",
            name="singular",
        ),
    ]
