# Generated by Django 5.2.5 on 2025-08-15 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0036_remove_yieldunit_singular"),
    ]

    operations = [
        migrations.RenameField(
            model_name="yieldunit",
            old_name="name",
            new_name="singular",
        ),
    ]
