# Generated by Django 5.2.5 on 2025-08-15 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0037_rename_name_yieldunit_singular"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversion",
            name="from_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conversions_from",
                to="manager.unit",
            ),
        ),
        migrations.AlterField(
            model_name="conversion",
            name="to_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conversions_to",
                to="manager.unit",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="manager.ingredient",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="manager.unit",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="classification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recipes",
                to="manager.classification",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="yield_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recipes",
                to="manager.yieldunit",
            ),
        ),
        migrations.AlterField(
            model_name="recipecost",
            name="yield_unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manager.yieldunit",
            ),
        ),
        migrations.AlterField(
            model_name="step",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manager.stepgroup",
            ),
        ),
    ]
