# Generated by Django 5.2.5 on 2025-08-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0038_alter_conversion_from_unit_alter_conversion_to_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='singular',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
