# Generated by Django 5.2.3 on 2025-07-08 11:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0007_alter_conversion_ingredient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversion",
            name="factor",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="conversion",
            name="ingredient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manager.ingredient",
            ),
        ),
        migrations.DeleteModel(
            name="UnitConversion",
        ),
    ]
