# Generated by Django 5.2.3 on 2025-07-08 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "manager",
            "0008_alter_conversion_factor_alter_conversion_ingredient_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversion",
            name="factor",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=7,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
