# Generated by Django 5.2.3 on 2025-07-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0010_alter_ingredientprice_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timer",
            name="duration",
            field=models.DurationField(),
        ),
    ]
