# Generated by Django 5.2.3 on 2025-07-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0012_alter_recipe_date_created_alter_recipe_date_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
