# Generated by Django 5.2.3 on 2025-07-13 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0014_alter_recipe_cuisine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cuisine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recipes",
                to="manager.cuisine",
            ),
        ),
    ]
