# Generated by Django 5.2.3 on 2025-07-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0017_itemcost"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemcost",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
