# Generated by Django 5.2.3 on 2025-07-22 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0019_recipecost"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipecost",
            name="recipe",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cost",
                to="manager.recipe",
            ),
            preserve_default=False,
        ),
    ]
