# Generated by Django 5.2.3 on 2025-07-26 02:49

import manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0023_alter_ingredient_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.FileField(
                upload_to=manager.models.image_upload_to,
                validators=[manager.models.validate_avif_extension],
            ),
        ),
    ]
